import Link from "next/link";

export default function AboutPage() {
  return <main className="page">
    <nav className="nav"><Link className="logo" href="/"><span className="logo-mark">✦</span> BirthdayWishora</Link><div className="nav-links"><Link href="/wishes">Explore Wishes</Link><Link className="nav-cta" href="/#generator">Create Wish</Link></div></nav>
    <section className="hero"><div className="hero-content"><div className="badge">✦ About BirthdayWishora</div><h1>Words for the moments<br/><span>that matter most.</span></h1><p>BirthdayWishora is a global birthday greeting platform built to make finding, creating and sharing the right words feel effortless.</p></div></section>
    <section className="category-section"><div className="section-heading"><div><span className="eyebrow">OUR PURPOSE</span><h2>Less searching. More meaning.</h2></div></div><div className="feature-strip" style={{padding:0,maxWidth:"none"}}><div><span>✦</span><b>Personal</b><p>Messages shaped around relationships, personality, memories and tone.</p></div><div><span>🌎</span><b>Global</b><p>Birthday wishes designed for people, cultures and languages around the world.</p></div><div><span>♡</span><b>Human</b><p>Technology should help people express feelings—not make them feel generic.</p></div></div></section>
    <section className="card-preview"><div className="preview-copy"><span className="eyebrow">FOUNDED BY</span><h2>Satpal Swami</h2><p>BirthdayWishora is an independent project created by Satpal Swami with a simple goal: make it easier for everyone to find the right words for the people they care about.</p><Link className="text-button" href="/contact">Get in touch →</Link></div><div className="card-stack"><div className="mini-card front"><span>BirthdayWishora</span><strong>Celebrate<br/>beautifully.</strong><small>Make every birthday unforgettable.</small></div></div></section>
    <section className="category-section" style={{paddingTop:0}}><div className="category-card" style={{maxWidth:620}}><span className="category-icon">✉</span><span><b>Official contact</b><small>satpalswami22742@gmail.com</small></span></div></section>
    <footer className="footer"><div><Link className="logo" href="/"><span className="logo-mark">✦</span> BirthdayWishora</Link><p>Make Every Birthday Unforgettable.</p><small>Created by Satpal Swami.</small></div><div className="footer-links"><Link href="/wishes">Wishes</Link><Link href="/cards">Cards</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></div><div className="footer-bottom">© {new Date().getFullYear()} BirthdayWishora · Satpal Swami.</div></footer>
  </main>;
}
