import Link from "next/link";
import {notFound} from "next/navigation";
import {SiteHeader,SiteFooter} from "@/components/site-shell";
import {BreadcrumbSchema,FAQSection,JsonLd} from "@/components/seo";
const languages={
en:{name:"English",native:"English",intro:"Find natural, ready-to-share birthday wishes in English for family, friends, partners and colleagues.",q:"How can I create a birthday wish in English?",a:"Choose a relationship and style in the BirthdayWishora wish library, then personalize the message with a name, age, language and memory."},
hi:{name:"Hindi",native:"हिन्दी",intro:"Discover birthday wishes for loved ones in Hindi, with warm and personal messages for every relationship.",q:"Can I personalize a Hindi birthday wish?",a:"Yes. Choose Hindi in the wish generator and add the recipient's name, age and a personal memory."},
hinglish:{name:"Hinglish",native:"Hinglish",intro:"Create natural Hinglish birthday messages that blend Hindi and English for modern, personal celebrations.",q:"What is a Hinglish birthday wish?",a:"A Hinglish birthday wish naturally combines Hindi and English so the message feels conversational and personal."},
es:{name:"Spanish",native:"Español",intro:"Explore birthday greeting ideas for family, friends and partners in Spanish.",q:"Can I make a Spanish birthday message personal?",a:"Yes. Choose Spanish in the generator and add the relationship, tone and personal details."},
fr:{name:"French",native:"Français",intro:"Find thoughtful birthday greeting ideas in French for the people who matter most.",q:"Can BirthdayWishora help with French birthday messages?",a:"Yes. Select French in the generator and personalize the message around the recipient and your relationship."},
de:{name:"German",native:"Deutsch",intro:"Create thoughtful birthday greeting ideas in German for family, friends and colleagues.",q:"Can I create a German birthday greeting?",a:"Yes. Select German in the generator and choose the relationship and style that fit your recipient."},
ar:{name:"Arabic",native:"العربية",intro:"Explore birthday greeting ideas in Arabic for family, friends, partners and special people.",q:"Can I personalize an Arabic birthday message?",a:"Yes. Select Arabic and provide the relationship and personal details you want reflected in the message."},
pt:{name:"Portuguese",native:"Português",intro:"Find birthday greeting ideas in Portuguese for heartfelt, funny, romantic and simple moments.",q:"Can I create a Portuguese birthday wish?",a:"Yes. Choose Portuguese in the generator and personalize the wish with relationship, tone and personal details."}
} as const;
export function generateStaticParams(){return Object.keys(languages).map(language=>({language}));}
export async function generateMetadata({params}:{params:Promise<{language:string}>}){const {language}=await params;const l=languages[language as keyof typeof languages];if(!l)return{};return{title:"Birthday Wishes in "+l.name,description:l.intro,alternates:{languages:Object.fromEntries(Object.keys(languages).map(code=>[code,"/wishes/language/"+code]))}};}
export default async function LanguagePage({params}:{params:Promise<{language:string}>}){const {language}=await params;const l=languages[language as keyof typeof languages];if(!l)notFound();const url="/wishes/language/"+language;const faqs=[{q:l.q,a:l.a},{q:"Who can I write a birthday wish for?",a:"BirthdayWishora covers Mom, Dad, siblings, best friends, partners, colleagues, children, teachers and someone special."},{q:"Can I share my birthday message?",a:"Yes. BirthdayWishora is designed for quick copying and sharing across common social and messaging platforms."}];return <main className="library-page"><SiteHeader/><BreadcrumbSchema items={[{name:"BirthdayWishora",url:"/"},{name:"Wish Library",url:"/wishes"},{name:"Birthday Wishes in "+l.name,url}]}/><JsonLd data={{"@context":"https://schema.org","@type":"CollectionPage",name:"Birthday Wishes in "+l.name,description:l.intro,url}}/><section className="library-hero language-landing"><span className="eyebrow">✦ {l.native.toUpperCase()} BIRTHDAY WISHES</span><h1>Birthday wishes<br/><span>in {l.name}.</span></h1><p>{l.intro}</p><div className="library-actions"><Link className="hero-button" href="/#generator">Create with Wishora AI →</Link><Link className="hero-link" href="/wishes">Explore all wishes</Link></div></section><section className="answer-block answer-block-wide"><span className="eyebrow">THE QUICK ANSWER</span><h2>Find the right birthday words in {l.name}.</h2><p>Choose who the message is for, select a style and personalize it with the details that make the birthday feel unique.</p><div className="topic-links"><Link href="/wishes/mom">For Mom</Link><Link href="/wishes/dad">For Dad</Link><Link href="/wishes/best-friend/funny">Funny</Link><Link href="/wishes/partner/romantic">Romantic</Link><Link href="/wishes/mom/emotional">Emotional</Link><Link href="/cards">Birthday Cards</Link></div></section><FAQSection items={faqs}/><SiteFooter/></main>;}
