create table if not exists public.languages (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null
);

create table if not exists public.wish_categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null
);

create table if not exists public.wish_styles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null
);

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  category_id bigint references public.wish_categories(id) on delete set null,
  style_id bigint references public.wish_styles(id) on delete set null,
  language_id bigint references public.languages(id) on delete set null,
  title text,
  content text not null,
  slug text unique,
  created_at timestamptz not null default now()
);

alter table public.languages enable row level security;
alter table public.wish_categories enable row level security;
alter table public.wish_styles enable row level security;
alter table public.wishes enable row level security;

create policy "public can read languages" on public.languages for select to anon, authenticated using (true);
create policy "public can read categories" on public.wish_categories for select to anon, authenticated using (true);
create policy "public can read styles" on public.wish_styles for select to anon, authenticated using (true);
create policy "public can read wishes" on public.wishes for select to anon, authenticated using (true);