create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.languages (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  is_active boolean not null default true
);

create table if not exists public.wish_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  is_active boolean not null default true
);

create table if not exists public.wish_styles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  is_active boolean not null default true
);

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.wish_categories(id) on delete restrict,
  style_id bigint not null references public.wish_styles(id) on delete restrict,
  language_id bigint not null references public.languages(id) on delete restrict,
  title text not null,
  content text not null,
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.wish_translations (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishes(id) on delete cascade,
  language_id bigint not null references public.languages(id) on delete restrict,
  title text not null,
  content text not null,
  unique (wish_id, language_id)
);

create table if not exists public.card_templates (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  preview_url text,
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_wishes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  wish_id bigint not null references public.wishes(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, wish_id)
);

create table if not exists public.generated_wishes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  category_id bigint references public.wish_categories(id) on delete set null,
  style_id bigint references public.wish_styles(id) on delete set null,
  language_id bigint references public.languages(id) on delete set null,
  recipient_name text,
  prompt text,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  template_id uuid references public.card_templates(id) on delete set null,
  title text,
  content text,
  image_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists wishes_category_idx on public.wishes(category_id);
create index if not exists wishes_style_idx on public.wishes(style_id);
create index if not exists wishes_language_idx on public.wishes(language_id);
create index if not exists wish_translations_language_idx on public.wish_translations(language_id);
create index if not exists saved_wishes_user_idx on public.saved_wishes(user_id);
create index if not exists saved_wishes_wish_idx on public.saved_wishes(wish_id);
create index if not exists generated_wishes_user_idx on public.generated_wishes(user_id);
create index if not exists generated_wishes_category_idx on public.generated_wishes(category_id);
create index if not exists generated_wishes_style_idx on public.generated_wishes(style_id);
create index if not exists generated_wishes_language_idx on public.generated_wishes(language_id);
create index if not exists user_cards_user_idx on public.user_cards(user_id);
create index if not exists user_cards_template_idx on public.user_cards(template_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'));
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_cards_set_updated_at on public.user_cards;
create trigger user_cards_set_updated_at before update on public.user_cards
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.languages enable row level security;
alter table public.wish_categories enable row level security;
alter table public.wish_styles enable row level security;
alter table public.wishes enable row level security;
alter table public.wish_translations enable row level security;
alter table public.card_templates enable row level security;
alter table public.saved_wishes enable row level security;
alter table public.generated_wishes enable row level security;
alter table public.user_cards enable row level security;

insert into public.languages (code,name) values
('en','English'),('hi','Hindi'),('hinglish','Hinglish'),('es','Spanish'),
('fr','French'),('de','German'),('ar','Arabic'),('pt','Portuguese')
on conflict (code) do nothing;

insert into public.wish_categories (slug,name) values
('mom','Mom'),('dad','Dad'),('brother','Brother'),('sister','Sister'),
('best-friend','Best Friend'),('partner','Partner'),('colleague','Colleague'),
('son','Son'),('daughter','Daughter'),('teacher','Teacher'),('someone-special','Someone Special')
on conflict (slug) do nothing;

insert into public.wish_styles (slug,name) values
('sweet','Sweet'),('emotional','Emotional'),('funny','Funny'),('romantic','Romantic'),
('cool','Cool'),('respectful','Respectful'),('short','Short & Simple'),('heart-touching','Heart-touching')
on conflict (slug) do nothing;

grant select on public.languages, public.wish_categories, public.wish_styles, public.wishes, public.wish_translations, public.card_templates to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.saved_wishes, public.generated_wishes, public.user_cards to authenticated;
grant insert on public.generated_wishes to anon;

drop policy if exists "public can read active languages" on public.languages;
create policy "public can read active languages" on public.languages for select to anon, authenticated using (is_active = true);
drop policy if exists "public can read active categories" on public.wish_categories;
create policy "public can read active categories" on public.wish_categories for select to anon, authenticated using (is_active = true);
drop policy if exists "public can read active styles" on public.wish_styles;
create policy "public can read active styles" on public.wish_styles for select to anon, authenticated using (is_active = true);
drop policy if exists "public can read active wishes" on public.wishes;
create policy "public can read active wishes" on public.wishes for select to anon, authenticated using (is_active = true);
drop policy if exists "public can read active translations" on public.wish_translations;
create policy "public can read active translations" on public.wish_translations for select to anon, authenticated
using (exists (select 1 from public.wishes w where w.id = wish_id and w.is_active = true));
drop policy if exists "public can read active card templates" on public.card_templates;
create policy "public can read active card templates" on public.card_templates for select to anon, authenticated using (is_active = true);

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "users can read own saved wishes" on public.saved_wishes;
create policy "users can read own saved wishes" on public.saved_wishes for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "users can save wishes" on public.saved_wishes;
create policy "users can save wishes" on public.saved_wishes for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "users can delete own saved wishes" on public.saved_wishes;
create policy "users can delete own saved wishes" on public.saved_wishes for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "users can read own generated wishes" on public.generated_wishes;
create policy "users can read own generated wishes" on public.generated_wishes for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "users can create generated wishes" on public.generated_wishes;
create policy "users can create generated wishes" on public.generated_wishes for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "guests can create generated wishes" on public.generated_wishes;
create policy "guests can create generated wishes" on public.generated_wishes for insert to anon with check (user_id is null);

drop policy if exists "users can read own cards" on public.user_cards;
create policy "users can read own cards" on public.user_cards for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "users can create own cards" on public.user_cards;
create policy "users can create own cards" on public.user_cards for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "users can update own cards" on public.user_cards;
create policy "users can update own cards" on public.user_cards for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "users can delete own cards" on public.user_cards;
create policy "users can delete own cards" on public.user_cards for delete to authenticated using ((select auth.uid()) = user_id);
